# ===========================================================================
# parse_yaml.cmake
#
# Converts a simple flat YAML config file into a CMake "initial cache" script
# that build.bat applies via `cmake -C <out>`.
#
# Usage (from build.bat):
#   cmake -DIN=config.yaml -DOUT=build/config_cache.cmake -P cmake/parse_yaml.cmake
#
# Supported YAML subset:
#   - whole-line comments starting with '#'
#   - blank lines (ignored)
#   - "key: value"  (value may be quoted with double quotes; quotes stripped)
#   - booleans normalized for BOOL keys: 1/0, on/off, true/false, yes/no
#
# Only keys in ACCEPT_KEYS are emitted; unknown keys print a warning.
# ===========================================================================

cmake_minimum_required(VERSION 3.10)

if(NOT DEFINED IN)
    message(FATAL_ERROR "parse_yaml.cmake: -DIN=<yaml path> is required")
endif()
if(NOT DEFINED OUT)
    set(OUT "build/config_cache.cmake")
endif()

if(NOT EXISTS "${IN}")
    message(FATAL_ERROR "parse_yaml.cmake: input YAML not found: ${IN}")
endif()

# Keys == CMake cache variables. BOOL_KEYS are emitted as CACHE BOOL; the
# remainder as CACHE STRING.
set(ACCEPT_KEYS
    # Feature toggles (booleans)
    USE_OPENAL USE_OPENAL_DLOPEN USE_VOIP USE_MUMBLE USE_CODEC_OPUS
    USE_RESTCLIENT BUILD_GRANGER BUILD_STATIC_LIBS USE_INTERNAL_SDL3
    USE_INTERNAL_JPEG
    # Build targets
    BUILD_CLIENT BUILD_SERVER BUILD_GAME_SO BUILD_GAME_QVM BUILD_RENDERER_OPENGL2
    # Product identity
    GAME_PRODUCT_VERSION GAME_PRODUCT_NAME
    # Backward compatibility (deprecated, but still accepted)
    TREM_PRODUCT_VERSION TREM_PRODUCT_NAME
    # QVM packaging
    QVM_VERSION_MAJOR QVM_VERSION_TAG QVM_VERSION_INCREMENT
)
set(BOOL_KEYS
    USE_OPENAL USE_OPENAL_DLOPEN USE_VOIP USE_MUMBLE USE_CODEC_OPUS
    USE_RESTCLIENT BUILD_GRANGER BUILD_STATIC_LIBS USE_INTERNAL_SDL3
    USE_INTERNAL_JPEG
    BUILD_CLIENT BUILD_SERVER BUILD_GAME_SO BUILD_GAME_QVM BUILD_RENDERER_OPENGL2
)

function(_accept_key key outvar)
    list(FIND ACCEPT_KEYS "${key}" idx)
    if(idx EQUAL -1)
        set(${outvar} 0 PARENT_SCOPE)
    else()
        set(${outvar} 1 PARENT_SCOPE)
    endif()
endfunction()

function(_is_bool_key key outvar)
    list(FIND BOOL_KEYS "${key}" idx)
    if(idx EQUAL -1)
        set(${outvar} 0 PARENT_SCOPE)
    else()
        set(${outvar} 1 PARENT_SCOPE)
    endif()
endfunction()

function(_normalize_bool val outvar)
    string(TOLOWER "${val}" v)
    if(v STREQUAL "on" OR v STREQUAL "yes" OR v STREQUAL "true")
        set(${outvar} 1 PARENT_SCOPE)
    elseif(v STREQUAL "off" OR v STREQUAL "no" OR v STREQUAL "false")
        set(${outvar} 0 PARENT_SCOPE)
    else()
        # Already numeric or anything else: pass through.
        set(${outvar} "${val}" PARENT_SCOPE)
    endif()
endfunction()

file(STRINGS "${IN}" lines)

set(count 0)
set(body "")
foreach(line ${lines})
    # Strip leading/trailing whitespace
    string(STRIP "${line}" line)
    if(line STREQUAL "")
        continue()
    endif()
    # Skip whole-line comments
    string(SUBSTRING "${line}" 0 1 first)
    if(first STREQUAL "#")
        continue()
    endif()

    # Split on the first ':'
    string(FIND "${line}" ":" colon_idx)
    if(colon_idx EQUAL -1)
        message(WARNING "parse_yaml: ignoring malformed line (no ':'): ${line}")
        continue()
    endif()

    math(EXPR val_idx "${colon_idx} + 1")
    string(SUBSTRING "${line}" 0 "${colon_idx}" key)
    string(SUBSTRING "${line}" "${val_idx}" -1 val)
    string(STRIP "${key}" key)
    string(STRIP "${val}" val)

    # Strip one layer of surrounding double quotes
    if(val MATCHES "^\"(.*)\"$")
        set(val "${CMAKE_MATCH_1}")
    endif()

    if(key STREQUAL "")
        continue()
    endif()

    _accept_key("${key}" accepted)
    if(NOT accepted)
        message(WARNING "parse_yaml: ignoring unknown key '${key}'")
        continue()
    endif()

    if(val STREQUAL "")
        message(WARNING "parse_yaml: empty value for '${key}' (skipped)")
        continue()
    endif()

    _is_bool_key("${key}" isbool)
    if(isbool)
        _normalize_bool("${val}" val)
        string(APPEND body "set(${key} ${val} CACHE BOOL \"from config.yaml\" FORCE)\n")
    else()
        string(APPEND body "set(${key} \"${val}\" CACHE STRING \"from config.yaml\" FORCE)\n")
    endif()

    math(EXPR count "${count} + 1")
endforeach()

file(WRITE "${OUT}"
    "# Auto-generated by cmake/parse_yaml.cmake from ${IN}\n"
    "# Do not edit by hand; edit ${IN} instead.\n"
    "${body}"
)

message(STATUS "config.yaml: ${count} option(s) applied -> ${OUT}")
