name: Build MacOS 10

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


jobs:
  build:

    runs-on: macos-10.15

    steps:
    - uses: actions/checkout@v3
    - name: dependencies
      run: echo no deps
    - name: make
      run: make -j

