name: Build Linux

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


jobs:
  build:

    runs-on: ubuntu-latest
    container: debian:oldstable-slim
    env:
      release_name: release-linux-x86_64

    steps:
    - uses: actions/checkout@v3
    - name: dependencies
      run: |
        apt update -y
        apt install -y -qq \
          make \
          build-essential \
          libgl1-mesa-dev \
          libsdl2-dev \
          libopenal-dev \
          libfreetype6-dev \
          zip \
          rsync
        # remove until libcurl is updated:
        #libcurl4-openssl-dev \
        #curl \
    - name: make
      run: USE_RESTCLIENT=1 USE_INTERNAL_LUA=1 USE_CURL_DLOPEN=0 make -j
    - name: download paks
      run: ./misc/download-paks.sh
    - name: change perms
      run: chmod -R ugo+rw build
    - name: upload binaries
      # only run if this was a tagged release (only works if separate job)
      # if: ( github.event_name == "create" ) && ( github.event.ref_type == 'tag' )
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.release_name }}
        path: ./build/${{ env.release_name }}.zip

