name: Build Windows 64-bit (MinGW)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    container: debian:oldstable-slim
    env:
      PLATFORM: mingw32
      release_name: release-mingw32-x86_64

    steps:
    - uses: actions/checkout@v3
    - name: dependencies
      run: |
        apt update -y
        apt install -y -qq \
          make \
          build-essential \
          mingw-w64 \
          libgl1-mesa-dev \
          libsdl2-dev \
          libcurl4-openssl-dev \
          libopenal-dev \
          libfreetype6-dev \
          zip \
          curl \
          rsync
    - name: make
      run: USE_RESTCLIENT=1 USE_INTERNAL_LUA=1 make -j
    - name: download paks
      run: ./misc/download-paks.sh
    - name: change perms
      run: chmod -R ugo+rw build
    - name: pack 
      run: cd ./build; zip -r $release_name.zip $release_name/
    - name: upload binaries
      # only run if this was a tagged release (only works if separate job)
      # if: ( github.event_name == "create" ) && ( github.event.ref_type == 'tag' )
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.release_name }}
        path: ./build/${{ env.release_name }}.zip
