name: Build Windows 64-bit (MinGW)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


jobs:
  build:

    runs-on: ubuntu-latest
    container: debian:oldstable-slim
    env:
      PLATFORM: mingw32

    steps:
    - uses: actions/checkout@v3
    - name: dependencies
      run: |
        apt update -y
        apt install -y -qq \
          make \
          build-essential \
          mingw-w64 \
          libgl1-mesa-dev \
          libsdl2-dev \
          libcurl4-openssl-dev \
          libopenal-dev \
          libfreetype6-dev \
          zip \
          curl \
          rsync
    - name: make
      run: USE_RESTCLIENT=1 USE_INTERNAL_LUA=1 make -j
    - name: download paks
      run: ./misc/download-paks.sh
    - name: change perms
      run: chmod -R ugo+rw build

